version: '3'

services:
  employees-postgres:
    image: postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: password

  employees-app:
    image: employees
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - employees-postgres
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://employees-postgres/postgres'
