package employees.employees.repository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

//@Component
public class DbInit implements CommandLineRunner {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Override
    public void run(String... args) {
        jdbcTemplate.execute("create table employees " +
                "(id int8 generated by default as identity, emp_name varchar(255), " +
                "primary key (id))");
        jdbcTemplate.execute(
                "insert into employees(emp_name) values ('John Doe')");
        jdbcTemplate.execute(
                "insert into employees(emp_name) values ('Jack Doe')");

    }
}
